### ISSUE TITLE
403 Forbidden on send_private_message and get_messages_in_conversation

### ISSUE THREAD

**Issue by matthausen** [isFakeAccount/psnawp#14]
Getting a 403 Client Error: Forbidden for url: https://us-gmsg.np.community.playstation.net/groupMessaging/v1/users/me/threadIds?withOnlineIds=my-online-id

The target profile is not private and the chat is already opened

**Comment by isFakeAccount** [comment]
sony disabled that endpoint and I don't know the new the endpoint 

https://github.com/isFakeAccount/psnawp/issues/9

https://github.com/Tustin/psn-php/issues/201

Sony is kinda the reason why I don't want to spend too much time on this wrapper because they could just one-day switch endpoint once again killing the project.
