### ISSUE TITLE
Access Denied on client 

### ISSUE THREAD

**Issue by HotGiardiniera** [isFakeAccount/psnawp#24]
Hi.

When running the first two steps in the ReadME I run into `PSNAWPForbidden`

Steps taken:
psnawp = PSNAWP('<64 character npsso code>')
client = psnawp.me()
print(client.online_id)  # Error here

Any insight into why this may happen?

**Comment by kerdion** [comment]
@isFakeAccount Hello, Sony changed the endpoint for the requests. Fortunately it's pretty much the same, but instead of .net it is now .com (i.e. https://m.np.playstation.net -> https://m.np.playstation.com)

@HotGiardiniera your script errors out because of this. 

P.S. if you need help in the future it is good practice to give more insight about your error, so that one can help you faster.

**Comment by HotGiardiniera** [comment]
@kerdion Thanks for the follow up. Can you provide insight into how you came about these new endpoint changes?

**Comment by kerdion** [comment]
I have an application online and today it started failing repeatedly, by analyzing the logs I guessed it was the endpoint so I used a rooted S8 and HTTP Toolkit to intercept the requests

**Comment by HotGiardiniera** [comment]
Thanks @kerdion, issues resolved on my fork

**Comment by isFakeAccount** [comment]
The issue should be fixed in `1.0.3`
