### ISSUE TITLE
All name history of the account 

### ISSUE THREAD

**Issue by dimgfsatttyggfr** [isFakeAccount/psnawp#85]
Is it possible through the account id to find all the previous names that the account had? If so, then how?

**Comment by isFakeAccount** [comment]
There is no endpoint for it afaik. I can only implement what the sony android app can do.

**Comment by dimgfsatttyggfr** [comment]
but there is this:

print(example_user_1.prev_online_id)

will it print previous online id? or how does it work?

**Comment by dimgfsatttyggfr** [comment]
@isFakeAccount

**Comment by isFakeAccount** [comment]
This is code remaining from previous refactor that I should have deleted. In previous versions of PSN API `online_id` was a property that fetched new id each time via API. So I thought it would be worth keeping around the online id that was passed by the user. 

The case in which it would be useful is lets say if you new the old gamertag of a user and you created user object using this old gamertag. `online_id` returns the latest gamertag and the `prev_online_id` returns the gamertag the user passed. 

In latest version this is largely irrelevant since when creating the User object the API fetches the new gamertag at starts and uses it til the lifetime of that object.
